# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171218_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number',
            new_name='name',
        ),
    ]
