# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='booking/%Y/%m/%d/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
