# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_bookingfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingfile',
            old_name='filename',
            new_name='name',
        ),
    ]
