# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180117_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BookingFile'),
        ),
    ]
