# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_booking_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Vip'),
        ),
    ]
