# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180123_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Vip'),
        ),
    ]
