# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180123_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='charge',
            field=models.IntegerField(default=0),
        ),
    ]
