# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_container_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='rate1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='rate2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='rate3',
            field=models.IntegerField(default=0),
        ),
    ]
