# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('crm', '0014_auto_20180126_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
        ),
    ]
