# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_bookingfile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='lifton',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='reloc',
            field=models.IntegerField(default=0),
        ),
    ]
