# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20180202_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ssr_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SSR Code'),
        ),
    ]
