# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_charge_extra_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_charge',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
